language: clojure

jdk:
- openjdk11

services:
- docker

cache:
  npm: true
  directories:
  - $HOME/.m2
  - clj-string-normalizer/node_modules

env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: "C+RnSKIyIXWaZaDfDhqBclXMB8NxWMNQ4ZfeOfI2CpaoH9An0vnuzctC9RyHvGUYJMwfZyfPExkqENW65EAJI5vxa8ynn2zTsmRB3uPHb8c500KMqwTElvysqp5xvEISKlgMEWDyt2KFuYg8JREGGzSKtrzbKnZlTKHar2LSYxF30bodxEk4hOh+HkwIAFjRFue50QWcG702j39t3u15WX93U2roySblUFHCsPEtjyNh/9z2lNW66uK4CJtVs0bGHcA0lDS+p9RHeQr+2tTi/Swq2zev/Wu+8s7zx6Pf6yl5YoEq8cQ97Pqeej3AM/jKbND60+8Ct7DUT/RWY1KfGdCjDVT3B9MPwhjy32AoQ5ciTWdrz1NSKoGB1TcU36BX1JjVs10hDvCk/MV91448U9jsYL+ux2w2ALAAO+7+NPE7NaeSFEU9zJ684Zxrs1lE1Y8KaQpe1kmUqAkrCD9Q+0Tx8GLiP3qTsefYmcElVy9CWER80pXb07t+Kl03S4bRIEQCUg9dDmyZc4vqDrT+VWO7//enr8VAYUrRRwbu5DSovbILJ0fEtQ/RxqSruVpMDt94V2wcwIRkXFeJ9ql2QOae8zU+4IMBgDkobbWY6URsY79GGbbcOWe0wRDWEpG6FyzJcIB8iQTGwyprff20QLtafEpiwM1I3fQbYytsdzA="
  # ARTIFACTORY_PASSWORD
  - secure: "WjhgzcO2mOD/i3SsXX3LfoQXPYFWDw/hfbqmqsGRcP+UFrg2bYBQ9MZhvscePwS+LYa1061KZEh8jKfg7UsFD3C64NTODOStrvgOLq+y7UKLXp7Og/LBHM0R2XLAgKkk73ufAtTlJMWme3EKstnVyDQNgI0xd5EqJD6A8gFeQnuTdaRcO7b6fNthRvB1XvIpEXWqoUOp/JzGwsnlP6vwMhi5J2bzZdYWNCDOD2CJ+JJB3WWWgJ07deZ55qOZfSJV4hbTDSwN1cGYtE5f4BBnqeFjCs+YWRbU9ufjqNyby/FXAdhS5tWGVf+qjPJJoE9pfBkUE/hZfc4N6RyJWyZxC0/v1/O6e86NS9uWZ9e9JTm8ZWYSkczRh45mpbqPhLhtNiIF5Z9aSMqd6kZSdgi/wTqijOXWeWdgcj/HlrgnRu68AHLhkAIDGq98wPgP5x2qiAc6uPziscZok618aKme4DiQs15/1PaAfkvDnKUWC1V8L+R5FKxDh21a0m/y6a+F9i8if3q0tdbrooqW49ejAA3y/WseA7scIHJSWTIlGQYv/eWDxGt50N2+CRj0mSlqxPPq2K7EXafVCuW1jGliSdk9PLqYU+DIlIxCoJm8TSG9dcaNxo06Clp9FRww0ioNhnN5bFflSTri2geNfjBXJJZN0YXQPly9APgET6/973k="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh

script: >-
  lein modules do clean, compile &&
  nvm install v12 &&
  nvm use v12 &&
  ./clj-string-normalizer/bin/cibuild.sh npm:install &&
  ./clj-string-normalizer/bin/cibuild.sh lint &&
  ./clj-string-normalizer/bin/cibuild.sh test

deploy:
- provider: script
  script: >-
    lein modules do deploy &&
    ./clj-string-normalizer/bin/cibuild.sh deploy
  skip_cleanup: true
  on:
    branch: OY-3036__elasticsearch-7
